force-app/main/default/objects/Attendees__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email Address of Attendee</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location(Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name Of The Event</description>
    <inlineHelpText>Enter the name of event</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location Of The Event</description>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeEmailHandler.cls
public class AttendeeEmailHandler {
    
    public static void sendConfirmationMail(List<Event_Attendee__c> attendees){

        Set<Id> attendeeIdSet = new Set<Id>();
        Set<Id> eventIdSet = new Set<Id>();

        for(Event_Attendee__c ea : attendees){
            AttendeeIdSet.add(ea.Attendee__c);
            EventIdSet.add(ea.Event__c);
        }

        Map<Id, Attendees__c> attendeeMap = new Map<Id, Attendees__c>([SELECT Id, Name, Email__c From Attendees__c WHERE  Id IN : attendeeIdSet]);
        Map<Id, Event__c> eventMap = new Map<Id, Event__c>([SELECT Id, Name__c, Start_Date_Time__c, Location__r.Name, Organizer__r.Name From Event__c WHERE  Id IN : eventIdSet]);

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Event_Attendee__c attendee : attendees){

            Attendees__c att = attendeeMap.get(attendee.Attendee__c);
            Event__c eve = eventMap.get(attendee.Event__c);



            String subject = 'Pass For The '+Eve.Name__c;
            String body = 'Dear '+Att.Name+',\n\n';

            body+='Thank you for registering for '+Eve.Name__c+' which will be Organized on '+Eve.Start_Date_Time__c+' at '+Eve.Location__r.Name+' We are excited to have you, see you at the event.\n\n';

            body += 'Thanks,\n' +Eve.Organizer__r.Name;

            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(new String[]{Att.Email__c});
            email.setSubject(subject);
            email.setPlainTextBody(body);
            emails.add(email);
        }

        List<Messaging.SendEmailResult> results = Messaging.sendEmail(emails, false);
        for(Messaging.SendEmailResult email : results){
            System.debug(email.isSuccess());
        }
    }
}