force-app/main/default/objects/Attendees__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email Address of Attendee</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location(Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <label>Max Seats</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name Of The Event</description>
    <inlineHelpText>Enter the name of event</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email Id of Event Organizer</description>
    <inlineHelpText>Enter Email Id of Event Organizer</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location Of The Event</description>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeEmailHandlerTest.cls
@isTest
public class AttendeeEmailHandlerTest {
    @isTest
    static void sendConfirmationMailTest(){
        Event_Organizer__c organizer = new Event_Organizer__c();
        organizer.Name = 'Test Organizer';
        insert organizer;

        Location__c location = new Location__c();
        location.Name = 'Test Location';
        insert location;

        Event__c event = new Event__c();
        event.Name__c = 'Test Event';
        event.Organizer__c = organizer.Id;
        event.Location__c = location.Id;
        event.Start_Date_Time__c = Datetime.now();
        event.End_Date_Time__c = Datetime.now().addDays(3);
        event.Max_Seats__c = 20;
        event.Live__c = true;
        insert event;

        Attendees__c attendee = new Attendees__c();
        attendee.Name = 'Test Attendee';
        attendee.Email__c = 'falak27dec@gmail.com';
        insert attendee;

        Event_Attendee__c eventAttendee = new Event_Attendee__c();
        eventAttendee.Attendee__c = attendee.Id;
        eventAttendee.Event__c = event.Id;
        insert eventAttendee;

        List<Event_Attendee__c> eventAttendeeList = [SELECT Id, Attendee__c, Event__c FROM Event_Attendee__c WHERE Id =: eventAttendee.Id];

        Test.startTest();
        AttendeeEmailHandler.sendConfirmationMail(eventAttendeeList);
        Test.stopTest();

        Integer invoice=Limits.getEmailInvocations();
        System.assertEquals(1,invoice,'Only one email is send');
    } 
}