force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Stores the Complete Stack Track about the Problem</description>
    <label>Log Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AddLogTest.cls
@isTest
public class AddLogTest {
    @isTest
    static void insertLogTest() {

        String logDetails = 'Test log details';
        String processName = 'Test process';

        Test.startTest();
        AddLog.insertLog(logDetails, processName);
        Test.stopTest();

        List<Error_Log__c> logs = [SELECT Id, Log_Date_Time__c, Log_Details__c, Process_Name__c FROM Error_Log__c];
        System.assertEquals(logDetails, logs[0].Log_Details__c );
        System.assertEquals(processName, logs[0].Process_Name__c);
    }
}