force-app/main/default/objects/Speaker__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createSpeaker.cls
@RestResource(urlMapping='/createSpeaker/*')

global class createSpeaker {

    @HttpPost
    global static String speakerCreation(String name, String email, String phone, String company){
        Speaker__c speaker = new Speaker__c(
            Name = name,
            Email__c = email,
            Phone__c = phone,
            Company__c = company
        );

        try {
            RestResponse res = RestContext.response;
            insert speaker;
            res.statusCode = 200;
            return 'Successful';
        } catch (Exception e) {
            RestResponse res = RestContext.response;
            res.statusCode = 400;
            return 'Insertion Failed';
            
        }


    }        
}