force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <label>Max Seats</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name Of The Event</description>
    <inlineHelpText>Enter the name of event</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email Id of Event Organizer</description>
    <inlineHelpText>Enter Email Id of Event Organizer</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventManagerTest.cls
@IsTest
private class EventManagerTest {

    @TestSetup
    static void createData(){

        Event_Organizer__c organizer = new Event_Organizer__c (
            Name = 'Test Name',
            Email__c = 'test@gmail.com'
        );

        insert organizer;

        Event__c event = new Event__c(
            Name__c = 'Test1',
            Start_Date_Time__c = Datetime.newInstance(2023, 5, 7, 12, 00, 00),
            Max_Seats__c = 10,
            Organizer__c = organizer.Id
        );

        insert event;
    }

    @IsTest
    static void eventManagerTest(){
        Test.startTest();
        RestContext.response = new RestResponse();
        EventsManager.getEvents();

        List<Object> results = (List<Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
        Map<string, object> resultDataMap = (Map<string, object>) results[0];
        Map<string,Object> eventDataMap = (Map<string,Object>) resultDataMap.get('event');

        System.assertEquals('Test1', String.valueOf(eventDataMap.get('name')));

        Test.stopTest();
    }
}