force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location(Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location Of The Event</description>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventRegistrationController.cls
public class EventRegistrationController {
    public Event_Organizer__c eventOrganizer {get; set;}

    public Location__c eventLocation {get; set;}

    public Event__c event { get;set;}

    public EventRegistrationController(){
        eventOrganizer = new Event_Organizer__c();
        eventLocation = new Location__c();
        event = new Event__c();      
    }

    public void save(){
        //To Save It;
        Savepoint sp = Database.setSavepoint();
        try{
            insert eventOrganizer;
            insert eventLocation;
            event.Organizer__c = eventOrganizer.Id;
            //Event__c is for Event Type
            if(event.Event__c != 'Virtual')
                event.Location__c = eventLocation.Id;
            insert event; 
        }catch(Exception e){
            Database.rollback(sp);
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
            AddLog.insertLog(e.getMessage(), 'Error Message');
        }
 
    }
}